# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 23:04
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathmapperapp', '0007_delete_worldborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='waypoints',
            field=django.contrib.gis.db.models.fields.LineStringField(default='LineString((0 0))', srid=4326),
            preserve_default=False,
        ),
    ]
